# /// script
# requires-python = "==3.10.*"
# dependencies = [
#   # Maximum-fidelity reconstruction of the environment the published meshes were
#   # generated in (Python 3.10, latest-on-or-before the 2026-02-02 mesh-gen date).
#   # The CANONICAL pins live in ../environment/postInstall (the CodeOcean-native
#   # definition); these mirror it so the script also runs standalone via uv.
#   "numpy==1.26.4",
#   "pandas==2.3.3",
#   "scipy==1.15.3",
#   "scikit-learn==1.7.2",
#   "trimesh==4.11.1",
#   "networkx==3.4.2",
#   "rtree==1.4.1",
#   "open3d==0.18.0",
#   "point-cloud-utils==0.34.0",
#   "tqdm==4.67.3",
#   # required transitively because `import lc_mesh` loads the figures/registration
#   # modules; the env (environment/postInstall) pins these identically.
#   "matplotlib==3.10.8",
#   "plotly==6.5.2",
#   "pot==0.9.6.post1",
# ]
# ///
"""Reproduce the locus coeruleus (LC) core mesh from the cell point data.

This is the entry point for regenerating the LC core mesh from scratch. It runs the
full pipeline — load the CCF-registered cell points, map local kNN density, select
the shell and interior populations, reconstruct the surface, and repair it into a
watertight mesh — and writes `new_core_mesh.obj`. It then (optionally) compares the
result to the published, distributed mesh and reports volume, surface-distance, and
topology differences.

This runs in the same pinned environment in which the published meshes were
generated, so when executed in the capsule it prints the actual difference between
the regenerated and published core mesh (volume, surface distance, topology). The
core-mesh recipe is fully specified (see `lc_mesh.config`) and regenerates to within
roughly ~0.1% in volume and a few microns of surface distance, with an identical
vertex count. Any residual is at the floating-point level in the surface
reconstruction (surfel fitting + watertight remeshing), not in the recipe — the
comparison printed on each run quantifies it exactly.

The nine percentile meshes (10-90) additionally involved per-mesh repair steps that
were applied interactively, by visual inspection, and were not recorded; those
meshes are therefore distributed as published artifacts rather than regenerated by
this script. The core-mesh recipe is fully specified and reproduced here.

Usage (on CodeOcean the datasets are mounted and the defaults resolve automatically):
    python code/reproduce_core_mesh.py                  # from the LC point table
    python code/reproduce_core_mesh.py --from-raw DIR   # from the raw .npy point calls
    python code/reproduce_core_mesh.py --csv P --published P --out DIR
"""
import argparse
import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("MPLBACKEND", "Agg")  # headless plotting for the comparison figure
REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))  # make lc_mesh importable

import trimesh  # noqa: E402
import lc_mesh  # noqa: E402

# Resolve inputs: CodeOcean capsule mounts if present, else a locally-staged copy.
_CAP = Path("/root/capsule/data")
MESH_ASSET = (_CAP / "LC_percentile_meshes" if _CAP.exists()
              else REPO / "results-c712751d-f744-4fe8-9657-93a7084eab22")
_OUT = (Path("/root/capsule/results/reproduced") if _CAP.exists()
        else REPO / "results" / "reproduced")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", default=str(MESH_ASSET / "LC_points.csv"),
                    help="LC point table with a kNN_percentile column")
    ap.add_argument("--published", default=str(MESH_ASSET / "new_core_mesh.obj"),
                    help="published new_core_mesh.obj to compare against (optional)")
    ap.add_argument("--out", default=str(_OUT), help="output directory")
    ap.add_argument("--from-raw", default=None,
                    help="instead of the point table, build LC points from the raw "
                         ".npy point calls under this data_root")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    # 1. obtain LC_only_points (with kNN_percentile)
    if args.from_raw:
        print(f"Building LC points from raw .npy under {args.from_raw} ...")
        df = lc_mesh.build_lc_points(args.from_raw)
    else:
        print(f"Loading points from {args.csv}")
        df = lc_mesh.load_lc_points_csv(args.csv)
        if "kNN_percentile" not in df.columns:
            sys.exit("CSV lacks kNN_percentile; use --from-raw to compute it.")
    print(f"  {len(df)} LC points")

    # 2. regenerate the core mesh
    t0 = time.time()
    mesh, _raw = lc_mesh.make_core_mesh(df, verbose=True)
    elapsed = time.time() - t0
    print(f"Regenerated core mesh in {elapsed:.1f}s: "
          f"{len(mesh.vertices)} verts, {len(mesh.faces)} faces, "
          f"watertight={mesh.is_watertight}, vol={mesh.volume/1e9:.6f} mm3")

    out_path = out / "new_core_mesh.obj"
    mesh.export(out_path)
    print(f"Saved -> {out_path}")

    report = {
        "n_lc_points": int(len(df)),
        "regenerate_seconds": round(elapsed, 1),
        "regenerated": lc_mesh.mesh_stats(mesh),
    }

    # 3. compare to published
    pub_path = Path(args.published)
    if pub_path.exists():
        published = trimesh.load(pub_path, process=False)
        print("Comparing to published mesh ...")
        cmp = lc_mesh.compare_meshes(mesh, published)
        report["comparison"] = cmp
        print("\n=== reproduction vs published ===")
        print(f"  volume:   regenerated {cmp['volume_mm3_regenerated']:.6f} mm3  vs  "
              f"published {cmp['volume_mm3_published']:.6f} mm3  "
              f"({cmp['volume_pct_diff']:.3f}% diff)")
        print(f"  surface:  mean {cmp['mean_surface_dist_um']:.3f} um, "
              f"median {cmp['median_surface_dist_um']:.3f} um, "
              f"p95 {cmp['p95_surface_dist_um']:.3f} um, "
              f"Hausdorff {cmp['hausdorff_um']:.3f} um")
        print(f"  topology: verts delta {cmp['n_vertices_delta']:+d}, "
              f"faces delta {cmp['n_faces_delta']:+d}")

        # side-by-side comparison figure
        fig_path = out / "comparison_regenerated_vs_published.png"
        lc_mesh.figures.plot_mesh_comparison(mesh, published, save_path=str(fig_path))
        report["comparison_figure"] = str(fig_path)
        print(f"  figure:   {fig_path}")
    else:
        print(f"(no published mesh at {pub_path}; skipping comparison)")

    report_path = out / "reproduction_report.json"
    report_path.write_text(json.dumps(report, indent=2))
    print(f"\nWrote report -> {report_path}")


if __name__ == "__main__":
    main()
