#!/usr/bin/env bash
set -e

# install updated version of code-server
VERSION=4.100.3
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -

# default behavior: extensions are installed here and reinstalled when capsule is rebuilt,
# alternative: install extensions manually inside capsule filesystem, saved across rebuilds
install_extensions=true

if $install_extensions; then
  mkdir -p /.vscode/extensions
  code-server --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter 
  code-server --extensions-dir=/.vscode/extensions --install-extension ms-python.python 
  code-server --extensions-dir=/.vscode/extensions --install-extension detachhead.basedpyright
else
  # move VS code extensions directory into capsule and symlink
  # (this may cause issues on the first run that will be solved by reloading VS code
  echo "mkdir -p /root/capsule/.vscode/extensions" >> /root/.profile
  ln -s /root/capsule/.vscode /.vscode
fi

# download and install vscode extension from file
# for extensions not available in the default open-vsx registry
download_and_install_extension() {
    publisher=$1
    name=$2
    version=$3
    file=/tmp/$publisher.$name.$version.vsix
    curl -fL http://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage \
        --output $file
    code-server --extensions-dir=/.vscode/extensions --install-extension $file
}

# comment out as needed:
# for code-server 4.100
download_and_install_extension github copilot 1.326.0
download_and_install_extension github copilot-chat 0.27.3

# python/jupyter/etc can be installed using the standard code-server command directly
code-server --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter
code-server --extensions-dir=/.vscode/extensions --install-extension ms-python.python

curl -LsSf https://astral.sh/uv/install.sh | \
    UV_INSTALL_DIR=/usr/local/bin sh
uv pip install --system git+https://github.com/AllenNeuralDynamics/aind-zarr-utils.git
# list of requirements
cat > /tmp/requirements.txt <<'REQ'
dask
dask-image
dask[distributed]
h5py
matplotlib
numpy<2
nbconvert
oauthlib
opencv-python
open3d
pandas
pillow
plotly
pot
point-cloud-utils
scikit-image
scikit-learn
scipy
seaborn
tifffile
torch
tqdm
umap-learn
rtree
trimesh
zarr
ipykernel
openpyxl
ipympl
statsmodels
antspyx
REQ

uv pip install --no-cache --system -r /tmp/requirements.txt && rm /tmp/requirements.txt
